# Generated by Django 2.1.1 on 2018-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('header', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
